POST http://localhost:8000/addOne
Content-Type: application/json

{
  "name": "value"
}
###
POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "Maksym_Los",
  "email": "maxlos@gmail.com",
  "phone": "88005553535",
  "password": "qwerty",
  "amount": "1000"
}
###
POST http://localhost:8000/signup
Content-Type: application/json

{
  "username": "danylo",
  "email": "9sarvas9@gmail.com",
  "phone": "76739549656",
  "password": "asdfggh",
  "amount": "100"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "Maksym_Los",
  "password": "q"
}

###
POST http://localhost:8000/test
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc
###
GET http://localhost:8000/users
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc
###
PUT http://localhost:8000/user?username=Maksym_Los
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc

{
  "amount": "1000"
}

###
DELETE http://localhost:8000/user?username=Maksym_Los
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc

###
POST http://localhost:8000/transact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1ha3N5bV9Mb3MiLCJyb2xlIjoidXNlciIsImlhdCI6MTY1NDY0NTI5MX0.0PjaVQNrARxAzhm8qySXBEVU_673WchpqSTX3OFXZic

{
  "sender": "Maksym_Los",
  "recipient": "danylodawn1",
  "amount": 1
}

###
GET http://localhost:8000/transactions
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc
###
GET http://localhost:8000/deleteAll
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZlbHljaGtvdnljaCIsImlhdCI6MTY1NDExMjE4MH0.ZqWi2uxEcFrJdxZm8KILwfkVoJqfd0VYP6biZY2xtRc

###